#!/bin/bash

errors=0

echo

mkdir source

for a in pages/*; do 
  b=${a/.txt/.rst}
  b=source/${b#pages/}
  echo -e "\e[1Fconverting \e[1m$a\e[m\e[K"
  if ! ./convert.py "$a" > "$b"; then
    echo
    errors=$((errors + 1))
  fi
done

echo Errors: $errors
